name: Buikld APK

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - uses: gradle/gradle-build-action@v2
    - run: gradle assembleDebug

    - name: Build with Gradle
      run: ./gradlew assembleDebug
